language: java

addons:
  sonarcloud:
    organization: "andryfailli-github"
      
jdk:
  - oraclejdk8

script:
  - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'