language: java

sudo: required

services:
  - docker

addons:
  sonarcloud:
    organization: "andryfailli-github"
    token:
      secure: $SONAR_TOKEN
    github_token:
      secure: $GITHUB_TOKEN
    branches:
      - master
      - develop
      - feature/*
      - hotfix/*
      - release/*
    
jdk:
  - oraclejdk8
  
before_script:
  - echo $REMINDME_FIREBASE_SERVER_KEY_JSON_BASE64 | base64 -d  > ./remindme-api/src/main/resources/firebase-server-key.json

script:
  - mvn -D"firebase.config.serverKey"="$REMINDME_FIREBASE_SERVER_KEY" clean jacoco:prepare-agent test org.pitest:pitest-maven:mutationCoverage jacoco:prepare-agent-integration verify package jacoco:report jacoco:report-integration sonar:sonar -Dsonar.pitest.mode=reuseReport coveralls:report -DrepoToken=$COVERALLS_TOKEN

  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'