language: java

addons:
  sonarcloud:
    organization: "andryfailli-github"
    token:
      secure: $SONAR_TOKEN
    github_token:
      secure: $GITHUB_TOKEN
    branches:
      - master
      - develop
      - feature/*
    
jdk:
  - oraclejdk8

script:
  - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent package jacoco:report coveralls:report sonar:sonar -DrepoToken=$COVERALLS_TOKEN
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'