language: java

sudo: required

services:
  - docker

addons:
  sonarcloud:
    organization: "andryfailli-github"
    token:
      secure: $SONAR_TOKEN
    github_token:
      secure: $GITHUB_TOKEN
    branches:
      - master
      - develop
      - feature/*
      - hotfix/*
      - release/*
    
jdk:
  - oraclejdk8

script:
  - mvn clean jacoco:prepare-agent test jacoco:prepare-agent-integration verify package jacoco:report jacoco:report-integration sonar:sonar coveralls:report -DrepoToken=$COVERALLS_TOKEN

  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'